version: '3.8'

services:
  investment-analyzer:
    build: .
    image: investment-analyzer:latest
    container_name: investment-analyzer
    ports:
      - "8501:8501"
    volumes:
      - investment-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  investment-data:
    driver: local
